version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
  selenium:
    image: 'selenium/standalone-firefox'
    ports:
      - "5555:5555"
    links:
      - "application"
  application:
    image: 'bitnami/joomla:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './www/joomla/addressbook:/bitnami/joomla/addressbook'
    links:
      - mariadb
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
       - PMA_ARBITRARY=1
       - MYSQL_HOST=mariadb:3306
       - PMA_HOST=mariadb:3306
#       - PMA_USER=root
#       - PMA_PASSWORD=
      restart: always
      ports:
       - 9999:80
      links:
       - "mariadb"
      volumes:
       - /sessions

volumes:
  mariadb_data:
    driver: local
  joomla_data:
    driver: local
  apache_data:
    driver: local
  php_data:
    driver: local
